name: Build, Push, and Deploy

on:
  push:
    branches:
      - main

env:
  # Use GitHub Container Registry (GHCR)
  REGISTRY: ghcr.io
  # Image name using <account>/<repo>
  IMAGE_NAME: ${{ github.repository }}

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
      id-token: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Log in to GitHub Container Registry
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u $GITHUB_ACTOR --password-stdin

      - name: Build Docker Image
        run: |
          docker build -t $REGISTRY/$IMAGE_NAME:latest .
          
      - name: Push Docker Image
        run: docker push $REGISTRY/$IMAGE_NAME:latest
        
  deploy-to-vps:
    runs-on: ubuntu-latest
    needs: build-and-push  # Ensures the build finishes before deploying

    steps:
      - name: SSH into VPS and Deploy Docker Container
        uses: appleboy/ssh-action@v1.2.0
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USER }}
          key: ${{ secrets.VPS_SSH_KEY }}
          script: |
            echo "Logging into GitHub Container Registry..."
            echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u $GITHUB_ACTOR --password-stdin
            
            echo "Pulling latest Docker image..."
            docker pull ghcr.io/${{ github.repository }}:latest

            echo "Stopping and removing old container..."
            docker stop sorcerer_landing_page || true
            docker rm sorcerer_landing_page || true

            echo "Running new container..."
            docker run -d --name sorcerer_landing_page -p 3001:3001 ghcr.io/${{ github.repository }}:latest
